server.port: 8090

spring:
  cache:
    type: hazelcast

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /db/h2

  jpa:
    show-sql: true
    properties.hibernate:
      show_sql: true
      format_sql: true

logging.level:
  org.springframework: DEBUG
  org.hibernate.SQL: DEBUG
